#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Dec  4 13:36:03 2018

@author: robert.mok
"""

# category - category of the feedback on that trial (not necessarily the dominant category for that direction). 0 for scene, 1 for face.                                         

# cat - 1 if the current category corresponds to the dominant category for this direction      
                                                      
# cat1 - 1 if the last category corresponds to the currently dominant category                                                                      

# resp - 1 if the subject responded according to the currently dominant category
        
# 'aresp' means 'faceresponse' or whatever 'a' happens to be. 1 if it was a 'face' response (regardless of what the button mapping happened to be - 
# we flipped between runs). This is the raw description of what the subject called the trial, regardless of what the cue or feedback happened to be.
          
#dir and dir1 scoring mirrors resp and resp1, but for the cue.(read more to see logic behin this)


#RM notes
# - so resp is the same as correct?


        
#later: read in subjective categories



#%%

import os
import glob
import pandas as pd

eventsDir='/Users/robert.mok/Documents/Postdoc_ucl/memsamp_fMRI/orig_events'
os.chdir(bidsDir)

subs = range(1,34) #33 subs - range doesn't include last number
for iSub in subs:
    print(f'{iSub:02d}')
    #iSub=1 #temp
    subNum=f'{iSub:02d}'
    fnames    = os.path.join(eventsDir, "sub-" + subNum + "*memsamp*." + 'tsv')
    datafiles = sorted(glob.glob(fnames))
    
    
    for iFile in datafiles:   
        #iFile = datafiles[0] #temp - testing
        dat=pd.read_csv(iFile, sep="\t")
        
        
        
        



